### ISSUE TITLE
Version management 

### ISSUE THREAD

**Issue by agrohn** [akunivalainen/SDL_repo#1]
Please use only a single copy of your solution that you develop incrementally. Now you have three separate directories in your repository, although they share same code base -> this works against using this tool. Each commit can be retrieved later using git, and you can use tags to name specific commits (say, Module1, Module2, Module3). 

It is by far simpler and more efficient, please get rid of separate module directories.

**Comment by akunivalainen** [comment]
One module folder that inculdes the project.
